products = [
    {
        '_id': '1',
        'name': 'Airpods Wireless Bluetooth Headphones 1',
        'image': '/images/airpods.jpg',
        'description': 'Lorem Ipsum demo text',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Airpods Wireless Bluetooth Headphones 2',
        'image': '/images/airpods.jpg',
        'description': 'Lorem Ipsum demo text',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '3',
        'name': 'Airpods Wireless Bluetooth Headphones 3',
        'image': '/images/airpods.jpg',
        'description': 'Lorem Ipsum demo text',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Airpods Wireless Bluetooth Headphones 4',
        'image': '/images/airpods.jpg',
        'description': 'Lorem Ipsum demo text',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
]
